{{ $client->nume }}, având sediul social in {{ $client->adresa }}, înregistrata la Registrul Comerțului sub nr. {{ $client->nr_ord_reg_com }}, având CUI {{ $client->cui }}, prelucrează date cu caracter personal.
<br/><br/>
Datele cu caracter personal vor fi colectate si prelucrate de către {{ $client->nume }} numai in măsura permisa prin Regulamentul General (UE) 2016/679 privind protecția persoanelor fizice în ceea ce privește prelucrarea datelor cu caracter personal și privind libera circulație a acestor date (GDPR)
<br/><br/>
Termeni in înțelesul Regulamentului General (UE) 2016/679:
<ul>
<li>„date cu caracter personal” înseamnă orice informații privind o persoană fizică identificată sau identificabilă („persoana vizată”); o persoană fizică identificabilă este o persoană care poate fi identificată, direct sau indirect, în special prin referire la un element de identificare, cum ar fi un nume, un număr de identificare, date de localizare, un identificator online, sau la unul sau mai multe elemente specifice, proprii identității sale fizice, fiziologice, genetice, psihice, economice, culturale sau sociale;</li>
<li>„prelucrare” înseamnă orice operațiune sau set de operațiuni efectuate asupra datelor cu caracter personal sau asupra seturilor de date cu caracter personal, cu sau fără utilizarea de mijloace automatizate, cum ar fi colectarea, înregistrarea, organizarea, structurarea, stocarea, adaptarea sau modificarea, extragerea, consultarea, utilizarea, divulgarea prin transmitere, diseminarea sau punerea la dispoziție în orice alt mod, alinierea sau combinarea, restricționarea, ștergerea sau distrugerea;</li>
<li>„restricționarea prelucrării” înseamnă marcarea datelor cu caracter personal stocate cu scopul de a limita prelucrarea viitoare a acestora;</li>
<li>„operator” înseamnă persoana fizică sau juridică, autoritatea publică, agenția sau alt organism care, singur sau împreună cu altele, stabilește scopurile și mijloacele de prelucrare a datelor cu caracter personal; atunci când scopurile și mijloacele prelucrării sunt stabilite prin dreptul Uniunii sau dreptul intern, operatorul sau criteriile specifice pentru desemnarea acestuia pot fi prevăzute în dreptul Uniunii sau în dreptul intern;</li>
<li>„persoană împuternicită de operator” înseamnă persoana fizică sau juridică, autoritatea publică, agenția sau alt organism care prelucrează datele cu caracter personal în numele operatorului;„parte terță” înseamnă o persoană fizică sau juridică, autoritate publică, agenție sau organism altul decât persoana vizată, operatorul, persoana împuternicită de operator și persoanele care, sub directa autoritate a operatorului sau a persoanei împuternicite de operator, sunt autorizate să prelucreze date cu caracter personal;</li>
<li>„consimțământ” al persoanei vizate înseamnă orice manifestare de voință liberă, specifică, informată și lipsită de ambiguitate a persoanei vizate prin care aceasta acceptă, printr-o declarație sau printr-o acțiune fără echivoc, ca datele cu caracter personal care o privesc să fie prelucrate.</li>
</ul>
{{ $client->nume }}, prelucrează datele personale colectate în temeiul încheierii și executării contractelor cu clienții, în vederea realizării intereselor legitime în relație cu scopurile menționate mai sus și în alte situații în temeiul consimțământului clienților. Scopurile colectării datelor sunt: informarea utilizatorilor/clienților (cumpărătorilor) privind situația contului lor de pe {{ $client->site_web }}, informarea utilizatorilor/clienților privind evoluția si starea comenzilor, evaluarea produselor si serviciilor oferite, activități comerciale, de promovare a produselor si serviciilor, de marketing, de publicitate, de media, administrative, de dezvoltare, de cercetare de piață, de statistică, de urmărire și monitorizare a vânzărilor și comportamentului consumatorilor.
<br/><br/>
Prelucrarea datelor cu caracter personal se face atat in regim propriu cat si utilizând produsele oferite de validsoftware.ro, care este furnizorul nostru de servicii web (găzduire website, realizare și administrare pagină web, promovare online și consultanță IT). validsoftware.ro asigură confidențialitatea datelor găzduite, iar politica de confidențialitate poate fi accesată aici – https://validsoftware.ro/politica-de-confidentialitate/.
<br/><br/>
Partenerii sunt atent selectați și se obligă să asigure, prin măsuri tehnice și organizatorice adecvate, prelucrarea datelor dumneavoastră conform prevederilor legale în vigoare privind protecția datelor și cu respectarea drepturilor dumneavoastră. Partenerilor le este interzis să utilizeze datele cu caracter personal primite pentru scopuri proprii sau comerciale sau să le transmită terților, cu excepția cazului în care terții acționează pentru atingerea scopurilor prelucrării descrise prin prezenta, caz în care aceleași condiții privind măsurile tehnice și organizatorice se aplica și acestora.
<br/><br/>
Prin citirea prezentei Politici de protecția datelor cu caracter personal și a Notei de Informare ați luat la cunoștință faptul că vă sunt garantate drepturile prevăzute de GDPR, respectiv:
<ul>
<li>dreptul la transparența informațiilor, a comunicărilor și a modalităților de exercitare a drepturilor dvs.;</li>
<li>dreptul la informare și acces la datele dvs. cu caracter personal;</li>
<li>dreptul la rectificare si dreptul la ștergerea datelor;</li>
<li>dreptul la restricționarea prelucrării;</li>
<li>dreptul la portabilitatea datelor;</li>
<li>dreptul la opoziție și de a nu fi supus unui procesul decizional individual automatizat;</li>
<li>dreptul de a vă adresa Autorității de Supraveghere (ANSPDCP) în caz de încălcare a drepturilor dvs. garantate de legislația privind protecția datelor cu caracter personal.</li>
</ul>
Pentru exercitarea drepturilor mai sus menționate sau pentru orice întrebare legată de modul în care datele dumneavoastră sunt utilizate ori dacă unele dintre datele despre dumneavoastră sunt incorecte, vă puteți adresa cu o cerere scrisă, datată și semnată către {{ $client->nume }}, {{ $client->adresa }}, în atenția responsabilului cu protecția datelor, sau la adresa de email {{ $client->email }}.
<br/><br/>
În cerere, vă rugăm să menționați dacă doriți ca informațiile să fie comunicate la o anumită adresă (poștală sau e-mail) sau printr-un serviciu de curierat care să asigure că veți primi personal informațiile. Va rugam sa țineți cont ca, înainte de a da curs oricărei astfel de cereri, ne rezervam dreptul de a va verifica identitatea, pentru a ne asigura ca solicitarea provine chiar din partea dumneavoastră. De asemenea, va este recunoscut dreptul de a va adresa justiției pentru orice încălcare a drepturilor dumneavoastră privind prelucrarea datelor cu caracter personal. Informațiile pe care ni le furnizați vor fi utilizate și stocate doar în scopul pentru care le-ați furnizat, pentru a administra, a sprijini și a evalua serviciile noastre, inclusiv pentru a preîntâmpina încălcarea securității sistemelor, și pentru respectarea legii și a termenilor noștri contractuali. În acest sens, {{ $client->nume }} va stoca datele dvs. în conformitate cu Politica de Retenție a Datelor care reglementează termene - limită prestabilite și bine documentate pentru diferite categorii de date cu caracter personal, în funcție de specificul operațiunilor pentru care sunt necesare. Mai mult, {{ $client->nume }} se asigură că datele cu caracter personal sunt adecvate, relevante și limitate la ceea ce este necesar pentru scopurile în care sunt prelucrate si de asemenea, se asigură că perioada pentru care datele cu caracter personal sunt stocate este limitată, iar la împlinirea termenelor limită, datele personale nu vor mai fi prelucrate în aceste scopuri.
<br/><br/>
{{ $client->nume }} poate furniza datele dumneavoastră cu caracter personal altor companii cu care se află în relații de parteneriat, dar numai în temeiul unui angajament de confidențialitate din partea acestora, prin care garantează că aceste date sunt păstrate în siguranță și că furnizarea acestor informații personale se face conform legislației în vigoare, după cum urmează: furnizori de servicii de curierat, servicii de bancare, alte companii cu care putem dezvolta programe comune de ofertare pe piață a produselor și serviciilor noastre, imputerniciti ai {{ $client->nume }} ce actioneaza in limitele si scopurile stabilite de {{ $client->nume }}, conform conditiilor din prezenta Politica.
<br/><br/>
<a href="https://www.{{ $client->site_web }}/termeni-si-conditii/"><em>Termeni și condiții</em></a>
<br/>
<a href="https://www.{{ $client->site_web }}/politica-de-confidentialitate/"><em>Politica de confidențialitate</em></a>
<br/>
<a href="https://www.{{ $client->site_web }}/protectia-datelor-cu-caracter-personal/"><em>Protecția datelor cu caracter personal</em></a>
<br/>
<a href="https://www.{{ $client->site_web }}/politica-cookies/"><em>Politica Pookies</em></a>